// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClKLIFGWGa1E0E-1Lw0tUmI7lr2gCxXl8',
    appId: '1:470708403851:web:b76e5abc3aca6703629e8e',
    messagingSenderId: '470708403851',
    projectId: 'fir-xflutterxauth-bd6df',
    authDomain: 'fir-xflutterxauth-bd6df.firebaseapp.com',
    storageBucket: 'fir-xflutterxauth-bd6df.firebasestorage.app',
    measurementId: 'G-BFSMHPKEPN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARiozjmakgRwZLeiIudKzjsd6J3eRMyUo',
    appId: '1:470708403851:ios:8698f9c3fe351278629e8e',
    messagingSenderId: '470708403851',
    projectId: 'fir-xflutterxauth-bd6df',
    storageBucket: 'fir-xflutterxauth-bd6df.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARiozjmakgRwZLeiIudKzjsd6J3eRMyUo',
    appId: '1:470708403851:ios:8698f9c3fe351278629e8e',
    messagingSenderId: '470708403851',
    projectId: 'fir-xflutterxauth-bd6df',
    storageBucket: 'fir-xflutterxauth-bd6df.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClKLIFGWGa1E0E-1Lw0tUmI7lr2gCxXl8',
    appId: '1:470708403851:web:5766a8e142390df2629e8e',
    messagingSenderId: '470708403851',
    projectId: 'fir-xflutterxauth-bd6df',
    authDomain: 'fir-xflutterxauth-bd6df.firebaseapp.com',
    storageBucket: 'fir-xflutterxauth-bd6df.firebasestorage.app',
    measurementId: 'G-RFGN06FS9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWmGFerF46llyoa2yT4LYjHBriYMgEkU',
    appId: '1:470708403851:android:6525908208488d54629e8e',
    messagingSenderId: '470708403851',
    projectId: 'fir-xflutterxauth-bd6df',
    storageBucket: 'fir-xflutterxauth-bd6df.firebasestorage.app',
  );

}